name: update dependency graph

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  dependency-graph:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout chryse
      uses: actions/checkout@v4
      with:
        repository: kivikakk/chryse
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Build and install chryse locally
      run: sbt publishLocal

    - name: Checkout this
      uses: actions/checkout@v4
    - uses: scalacenter/sbt-dependency-submission@v2
